version: 2.1

executors:
  docker: # Docker using the Base Convenience Image
    docker:
      - image: cimg/base:stable
  linux:
    machine:
      image: ubuntu-2004:202107-02
  windows:
    machine:
      image: win/default

orbs:
  node: circleci/node@4.7
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: yarn
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: yarn test

workflows:
  test_pipeline:
    jobs:
      - test:
          matrix:
            parameters:
              os: ["windows", "linux"]
              node-version: ["14.x", "16.x"]
